import { Verifier, VerifierStatusEnum } from "../types/verifier";

export const verifiers: Verifier[] = [
  {
    id: "1",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.ACTIVE,
  },
  {
    id: "2",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.PENDING,
  },
  {
    id: "3",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.ACTIVE,
  },
  {
    id: "4",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.DEACTIVATED,
  },
  {
    id: "5",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.ACTIVE,
  },
  {
    id: "6",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.DEACTIVATED,
  },
  {
    id: "7",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.ACTIVE,
  },
  {
    id: "8",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.PENDING,
  },
  {
    id: "9",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.DEACTIVATED,
  },
  {
    id: "10",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.ACTIVE,
  },
  {
    id: "11",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.DEACTIVATED,
  },
  {
    id: "12",
    firstName: "Temitope",
    lastName: "Adejumoke",
    phoneNumber: "+234800 000 0000",
    partner: "The Place",
    location: "Festac",
    status: VerifierStatusEnum.PENDING,
  },
];
